name: Release CI

on:
  push:
    branches: [ ambf-1.0-python3-fix ]
  pull_request:
    branches: [ ambf-1.0-python3-fix ]

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      
      - name: Build docker image
        run: |
          docker build --tag=ambf .